### ISSUE TITLE
Why use createKeyframes？

### ISSUE THREAD

**Issue by peoplesing1832** [jlkiri/react-easy-flip#25]
Hello, I am learning your project code recently. Why not use the start state and end state directly？Similar to 👇

```js

const player = el.animate([
  { transform: `translateY(${invert}px)` },
  { transform: 'translateY(0)' }
], {
  // ....
});
```

**Comment by jlkiri** [comment]
this is because custom easing functions are supported. so each keyframe is calculated using math from one of the functions in `src/easings.ts`.

**Comment by peoplesing1832** [comment]
> this is because custom easing functions are supported. so each keyframe is calculated using math from one of the functions in `src/easings.ts`. When using only start state and end state directly you can only choose from default easings, like 4 or 5 of them.

Thank you very much 💗
