### ISSUE TITLE
Smooth transition for animated in/out

### ISSUE THREAD

**Issue by hongnk** [jlkiri/react-easy-flip#31]
In the animated in/out sample, after one shape is removed the remaining shapes will just jump. Is it possible to make them to smoothly transition to new positions?

**Comment by jlkiri** [comment]
It's currently not possible with just with library, but you can combine it with [`use-animate-presence`](https://github.com/jlkiri/use-animate-presence) to achieve the effect, here's an example with code: https://github.com/jlkiri/use-animate-presence#arbitrary-number-of-animatable-items

**Comment by hongnk** [comment]
Thank you I tried to adapt use-animate-presence to shared layout sample and it worked great, although it looks a little complex. Hope this can be integrated into the main lib.
